eureka:
  client:
    serviceUrl:
      defaultZone: http://qin.local:8761/eureka/
  instance:
    hostname: qin.local
server:
  port: 8765
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 5000
