eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
        hostname: qin.local
server:
  port: 8764
spring:
  application:
    name: service-ribbon