server:
    port: 8761

eureka:
    instance:
        hostname: qin.local
        instance-id: ${eureka.instance.hostname}:${server.port}
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
    level: debug
spring:
    util:
        timeout:
            sec: 5