server:
    port: 8761

eureka:
    instance:
        hostname: qin.local
        prefer-ip-address: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8763/eureka/
logging:
    level: debug
spring:
    application:
        name: eureka-server
    util:
        timeout:
            sec: 5